name: Testing and Versioning 

on:
  push:
    branches:
      - "**" 
  pull_request:
    branches:
      - main

env:
  FORCE_COLOR: 2

jobs:
  prettier:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.0
        with:
           prettier_options: --write './src/**/*.{ts,tsx}'
  release:
    name: Versioning and possible release
    runs-on: ubuntu-18.04
    needs: prettier 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm i
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0
        run: npx semantic-release
